@LibraryManagementSystem_HostAddress = https://localhost:7213
// CREATE
POST {{LibraryManagementSystem_HostAddress}}/api/Users
Content-Type: application/json

{
  "username": "JohnDoe",
  "email": "john.doe@example.com",
  "hashedPassword": "hashed_password_value",
  "phone": "1234567890",
  "address": "123 Main Street, City, Country",
  "userPermissionsList": [
    1,
    2,
    3
  ]
}

###
// READ
GET {{LibraryManagementSystem_HostAddress}}/api/Users
Accept: application/json

###

GET {{LibraryManagementSystem_HostAddress}}/api/Users/1
Accept: application/json

###

// UPDATE

###

// DELETE

###

